# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20170407_0149'),
        ('Products', '0005_auto_20170407_0149 2'),
    ]

    operations = [
    ]
